### ISSUE TITLE
[ERROR] setBlocked() missing from CCHyprlandCtmControlManagerV1 when building on Gentoo with Hyprland 0.46.2

### ISSUE THREAD

**Issue by chrissolanilla** [hyprwm/hyprsunset#39]
Hello, I’m running into a build error on Gentoo when trying to compile Hyprsunset.

System versions:

    Hyprland: 0.46.2

    hyprwayland-scanner: 0.4.4

    hyprland-protocols: 0.4.0

    hyprutils: 0.7.1

I’m building using cmake and ninja, but I receive the following error:

`hyprsunset/src/Hyprsunset.cpp:97:32: error: ‘class CCHyprlandCtmControlManagerV1’ has no member named ‘setBlocked’`

It seems like my version of hyprlang or related Hyprland libraries dosent contain the `setBlocked()` method. However, the README says the project requires hyprland >= 0.45.0, and I’m on 0.46.2, so I expected this to work.

I also ran `git submodule update --init --recursive` but it looks like Hyprsunset doesn't include any submodules so I don't think thats the issue.

Could you clarify which version of hyprlang or hyprutils or whatever this depends on?

**Comment by vaxerski** [comment]
> hyprland-protocols: 0.4.0

this your problem, outdated as shit. Hyprland outdated too. Everything outdated.

**Comment by vaxerski** [comment]
hyprsunset works with 0.46 but you're building too new hyprsunset.
